export const cardContent=[
    {
        team1: 'A.P.R',
        team2: 'Rayon',
        when: 'Sunday 12-05-2021',
        time: '06:00 PM',
        where: 'Amahoro National stadium',
        price: '5000 Rwf',
        remainingSeats: 9999,
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.`,
        image:'https://firebasestorage.googleapis.com/v0/b/tickets-app-4626d.appspot.com/o/test%2Ftest%2Fapr-vs-rayon.png?alt=media&token=8780e111-8c2a-4225-a0e0-0ecbfb4e826e',
    },
    {
        team1: 'Rwanda',
        team2: 'Congo',
        when: 'Sunday 12-05-2021',
        time: '06:00 PM',
        where: 'National stadium',
        price: '5000 Rwf',
        remainingSeats: 1000,
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.`,
         image:'https://firebasestorage.googleapis.com/v0/b/tickets-app-4626d.appspot.com/o/test%2Ftest%2Frwanda-vs-congo.jpg?alt=media&token=966f2cca-0152-4684-ab72-5cb4155208bb',
    },
    {
        team1: 'Sun Rise',
        team2: 'The Juniors',
        when: 'Sunday 12-05-2021',
        time: '06:00 PM',
        where: 'Kigali Arena',
        price: '5000 Rwf',
        remainingSeats: 22222,
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.`,
        image: 'https://firebasestorage.googleapis.com/v0/b/tickets-app-4626d.appspot.com/o/test%2Ftest%2FScreenshot%202021-01-31%20230525.png?alt=media&token=d4034dc4-901f-4395-9b4d-f7a076d5004e',
    },
    
];


export const ticketCardContent=[
    {
        team1: 'A.P.R',
        team2: 'Rayon',
        dateOfEvent: 'Sunday 12-05-2021',
        timeOfEvent: '06:00 PM',
        dateOfPurchase: 'Sunday 12-05-2021',
        timeOfPurchase: '06:00 PM',
        address: 'Amahoro National stadium',
        price: '5000 Rwf',
        seatNumber: 99,
        QRCodeImage:'https://firebasestorage.googleapis.com/v0/b/tickets-app-4626d.appspot.com/o/test%2Ftest%2Fqr.png?alt=media&token=a54a0f23-2086-48a1-8372-5957ad39e46a',
    },
    {
        team1: 'Rwanda',
        team2: 'Congo',
        dateOfEvent: 'Sunday 12-05-2021',
        timeOfEvent: '06:00 PM',
        dateOfPurchase: 'Sunday 12-05-2021',
        timeOfPurchase: '06:00 PM',
        address: 'Amahoro National stadium',
        price: '5000 Rwf',
        seatNumber: 99,
        QRCodeImage:'https://firebasestorage.googleapis.com/v0/b/tickets-app-4626d.appspot.com/o/test%2Ftest%2Fqr.png?alt=media&token=a54a0f23-2086-48a1-8372-5957ad39e46a',
    },
    {
        team1: 'Rwanda',
        team2: 'Uganda',
        dateOfEvent: 'Sunday 12-05-2021',
        timeOfEvent: '06:00 PM',
        dateOfPurchase: 'Sunday 12-05-2021',
        timeOfPurchase: '06:00 PM',
        address: 'Amahoro National stadium',
        price: '5000 Rwf',
        seatNumber: 99,
        QRCodeImage:'https://firebasestorage.googleapis.com/v0/b/tickets-app-4626d.appspot.com/o/test%2Ftest%2Fqr.png?alt=media&token=a54a0f23-2086-48a1-8372-5957ad39e46a',
    },
    {
        team1: 'Burundi',
        team2: 'Rwanda',
        dateOfEvent: 'Sunday 12-05-2021',
        timeOfEvent: '06:00 PM',
        dateOfPurchase: 'Sunday 12-05-2021',
        timeOfPurchase: '06:00 PM',
        address: 'Amahoro National stadium',
        price: '5000 Rwf',
        seatNumber: 99,
        QRCodeImage:'https://firebasestorage.googleapis.com/v0/b/tickets-app-4626d.appspot.com/o/test%2Ftest%2Fqr.png?alt=media&token=a54a0f23-2086-48a1-8372-5957ad39e46a',
    },
    
]
