export const MENU_SHOW = 'SHOW_MENU';
export const MENU_HIDE = 'HIDE_MENU';

export const DISPLAY_CONTENT = 'DISPLAY_CONTENT';
export const HOME_MENU_CONTENT = 'HOME_MENU_CONTENT';
export const PURCHASE_MENU_CONTENT = 'PURCHASE_MENU_CONTENT';

export const MONTHLY_NASA_DATA_PENDING = 'MONTHLY_NASA_DATA_PENDING';
export const MONTHLY_NASA_DATA_SUCCESS = 'MONTHLY_NASA_DATA_SUCCESS';
export const MONTHLY_NASA_DATA_FAILURE = 'MONTHLY_NASA_DATA_FAILURE';

